#!/bin/sh

#Run this first then comment
#chown root:root /
#chmod 755 /
#passwd root
#echo Vegeta > /etc/hostname
#echo "LANG=en_US.UTF-8" > /etc/locale.conf
#echo "en_US.UTF-8 UTF-8" >> /etc/default/libc-locales

#uncomment this and rerun a second time
#dd bs=512 count=4 if=/dev/urandom of=/boot/volume.key
#cryptsetup luksAddKey /dev/nvme0n1p2 /boot/volume.key
#chmod 000 /boot/volume.key
#chmod -R g-rwx,o-rwx /boot
#echo "voidlinux /dev/sda2 /boot/volume.key luks" >> /etc/crypttab
#echo "install_items+=\" /boot/volume.key /etc/crypttab \"" >> /etc/dracut.conf.d/10-crypt.conf

#grub-install /dev/dev/sda
#xbps-reconfigure -f linux4.19
